name: daily-checkin
on:
schedule:
- cron: '0 0 * * *' # 每天 08:00 Asia/Shanghai
workflow_dispatch:

jobs:
run:
runs-on: ubuntu-latest
steps:
- name: Checkout
uses: actions/checkout@v4

  - name: Setup Python
    uses: actions/setup-python@v5
    with:
      python-version: '3.11'

  - name: Install deps
    run: pip install -U requests

  - name: Run checkin
   
env:
ACCOUNTS: ${{ secrets.ACCOUNTS }}
TG_BOT_TOKEN: ${{ secrets.TG_BOT_TOKEN }}
TG_CHAT_ID: ${{ secrets.TG_CHAT_ID }}
run: |
python - <<'PY'
import os, json, requests
accounts = json.loads(os.getenv('ACCOUNTS', '[]'))
print('workflow OK; accounts:', len(accounts))
# TODO: 在这里实现登录+签到逻辑，并用 TG_BOT_TOKEN/TG_CHAT_ID 发送结果
PY
