name: daily-checkin
on:
  schedule:
    - cron: '0 0 * * *'  # 08:00 Asia/Shanghai
  workflow_dispatch:

jobs:
  freecloud:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Python 3.11
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -U requests

      - name: Run FreeCloud check-in
        env:
          ACCOUNTS: ${{ secrets.ACCOUNTS }}
        run: |
          python scripts/freecloud_checkin.py
