name: FreeCloud Daily Check-in

on:
  workflow_dispatch:
  schedule:
    - cron: '0 0 * * *'  # 08:00 Asia/Shanghai

jobs:
  checkin:
    runs-on: ubuntu-latest
    timeout-minutes: 15
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install requests beautifulsoup4

      - name: Telegram test
        if: ${{ secrets.TELEGRAM_BOT_TOKEN && secrets.TELEGRAM_CHAT_ID }}
        run: |
          curl -sS -X POST "https://api.telegram.org/bot${{ secrets.TELEGRAM_BOT_TOKEN }}/sendMessage" \
            -H 'Content-Type: application/json' \
            -d "{\"chat_id\": \"${{ secrets.TELEGRAM_CHAT_ID }}\", \"text\": \"Test from GitHub Actions $(date -u)\"}" \
            -w "\nHTTP: %{http_code}\n"

      - name: Run FreeCloud check-in
        env:
          ACCOUNTS: ${{ secrets.ACCOUNTS }}
          TELEGRAM_BOT_TOKEN: ${{ secrets.TELEGRAM_BOT_TOKEN }}
          TELEGRAM_CHAT_ID: ${{ secrets.TELEGRAM_CHAT_ID }}
        run: |
          python scripts/freecloud_checkin.py
