name: daily-checkin
on:
schedule:
- cron: '15 1 * * *' # 每天 01:15 UTC 触发；若要 08:00 Asia/Shanghai，请用 '0 0 * * *'
workflow_dispatch:

jobs:
run:
runs-on: ubuntu-latest
steps:
- name: Setup Python
uses: actions/setup-python@v5
with

:
python-version: '3.11'

  - name: Install deps
    run: pip install -U requests

  - name: Run checkin
    env:
      ACCOUNTS: ${{ secrets.ACCOUNTS }}
      TG_BOT_TOKEN: ${{ secrets.TG_BOT_TOKEN }}
      TG_CHAT_ID: ${{ secrets.TG_CHAT_ID }}
    run: |
      python - <<'PY'
      import os, json, time, requests
      print("workflow OK; accounts:", len(json.loads(os.getenv("ACCOUNTS","[]"))))
      # TODO: 在这里加入登录+签到逻辑，并用 TG_BOT_TOKEN/TG_CHAT_ID 发送通知
      PY
